### ISSUE TITLE
1.7.6 wallet issue

### ISSUE THREAD

**Issue by tonedepear** [blur-network/blur#24]
Mining bat from 1.7.5 and previous doesn't work.  
I get :  Unknown command: logger %loc    %msg

Opening wallet from 1.7.5 fails on invalid password, but create new wallet works, and from that, start_mining works and starts mining in daemon ok. But old wallet can't be opened.

**Comment by vimichan** [comment]
> Mining bat from 1.7.5 and previous doesn't work.
> I get : Unknown command: logger %loc %msg
> 
> Opening wallet from 1.7.5 fails on invalid password, but create new wallet works, and from that, start_mining works and starts mining in daemon ok. But old wallet can't be opened.

I got the same question that opening wallet fails on invalid password.  Please tell me how to solve it.

**Comment by blur-network** [comment]
<b>For the errors when running blurd.exe with startup flags on Windows:</b>
If you are seeking to run the daemon with start-up flags (i.e. `--start-mining` or similar) the argument for the flag must be passed with an `=` sign instead of a space. Such that, what would have previously been written `--log-level 3` must now be written `--log-level=3`. Similarly, to start mining to an address in daemon, the following is an example of the correct syntax: 
Using cmd.exe: `blurd.exe --start-mining=<address> --mining-threads=<# of threads>`
Fill the bracketed areas with your subjective values, omitting the brackets. 

Using powershell: `.\blurd.exe --start-mining=<address> --mining-threads=<# of threads>`

<b>For the wallet password issue</b>
You'll need to restore your wallet from the 25-word mnemonic seed, due to a change in the way passwords are handled.

The following is from a user on our bitcointalk.org thread: 

In case you didn't write down your 25-word mnemonic, here's how to get it back and restore the wallet under the new version:

* Open the blur-wallet-cli.exe of an older version
* Sign in to your wallet
* Type encrypted_seed and hit enter
* Enter your password again and hit enter
* Hit enter twice (unless you have an optional seed encryption passphrase)
* Copy the 25 words
* Go to the folder where you saved the files of the newest version (v0.1.7.6)
* Type powershell in the address bar of that folder and hit enter
* Type .\blur-wallet-cli.exe --restore-deterministic and hit enter
* Create a wallet file and paste the 25 word mnemonic when prompted (it asks you to paste it line by line)
* You should have the new wallet files in the folder

**Comment by blur-network** [comment]
Closing due to less requests for help regarding the wallet password issues. Will reopen if that changes
