### ISSUE TITLE
libnorm-dev does not exist in Ubuntu 16.04

### ISSUE THREAD

**Issue by leto** [blur-network/blur#32]
The line from readme cannot be copy+pasted to install dependencies on 16.04, because libnorm-dev does not exist. It also does not seem to be needed, as compiling works fine when removing that from the apt-get line.

**Comment by who-biz** [comment]
This was fixed in 93e850899cf3d39c9c36daacca41c8e04dd4c6f8 yesterday, despite me not seeing this until now.  

libnorm-dev is only required when zeromq is built using libnorm-dev.  it appears that the bionic package was built using the library, but that debian 9 and ubuntu 16 packages were built without the library.
