### ISSUE TITLE
Enhancement: read electrum seeds from STDIN or a file

### ISSUE THREAD

**Issue by leto** [blur-network/blur#53]
Currently when using

`--restore-deterministic-wallet --electrum-seed "the seedphrase"`

it means that the seedphrase can be seen in a trivial `ps` output and will also potentially be in shell history. This is not just a short running process, when recovering a wallet and leaving it running, the seedphrase can be seen in the process arguments until the wallet is exited.

Instead of the current behavior of giving an error if no seedphrase is specified, the wallet would attempt to read it from STDIN. There could also be a new --electrum-seed-file as well.

**Comment by who-biz** [comment]
Thanks for letting me know @leto. I'll be pushing back the fork height while I work out a patch.  Sorry, I just saw this now.

**Comment by who-biz** [comment]
Does the wallet exit properly? The NDEBUG code I just removed from `CMakeLists.txt` was blocking a lot of exceptions it looks like

**Comment by who-biz** [comment]
In the past, I've always recommended people use the `--restore-deterministic` option, and follow the prompts, which request entering the seed phrase one line at a time. That's the same behavior you're saying would be best to include with the `--electrum-seed` option as well, correct?

**Comment by leto** [comment]
@who-biz I didn't really know how to recover/import my wallet to a new machine, so I just read --help and after doing the wrong thing various times, I figured out something that worked.

I was confused about "electrum seed", because I used the seedphrase generated by a blur full node, but I either failed to use --restore-deterministric or it wasn't clear that I should have used that.

If I should just use that, maybe no work is needed. What is the difference between  --restore-deterministric and --electrum-seed ?

**Comment by leto** [comment]
@who-biz typing `exit` did work correctly. I am on the f31b8ac commit of master branch

**Comment by who-biz** [comment]
>If I should just use that, maybe no work is needed. What is the difference between --restore-deterministric and --electrum-seed ?

As nearly as I can tell, not much.  Electrum style seeds are used as default in our codebase, by inheritance from XMR, since launch.  From that information, they should be the same command.

So the fix, if that's the case, would just be a matter of removing the --electrum-seed option completely, and updating the help text since you've let me know that its lacking proper instruction.

**Comment by who-biz** [comment]
Something that was waiting down the pipeline as well, was separating the viewkey and spendkey so that the viewkey is not deterministic (derived from the spendkey, of which the mnemonic is a representation).  I think this is a disavowal of established best-practices, and to the best of my understanding, was eliminated because a single mnemonic couldn't be used to generate two distinctly unrelated keypairs.  That was a problem for MyMonero mainly, and general usability.  But since, we don't have any plans to use any solutions that are like MyMonero's requirement to divulge your keys... I dont see anything but good that could come from a reversion to that practice.  A loss in usability maybe, but a worthwhile one for a gain in security.

**Comment by who-biz** [comment]
> @who-biz typing exit did work correctly. I am on the f31b8ac commit of master branch

I'll give the wallet some testing with the latest commits to master, since I just removed the NDEBUG conditional from CMakeLists.txt.  it seems that was surpressing an exception in p2p on daemon exit, so I'll need to poke around a bit.

**Comment by who-biz** [comment]
> @who-biz I didn't really know how to recover/import my wallet to a new machine, so I just read --help and after doing the wrong thing various times, I figured out something that worked.
> 
> I was confused about "electrum seed", because I used the seedphrase generated by a blur full node, but I either failed to use --restore-deterministric or it wasn't clear that I should have used that.
> 
> If I should just use that, maybe no work is needed. What is the difference between --restore-deterministric and --electrum-seed ?

Lastly, you can find the procedure for the seed phrase restore here https://github.com/blur-network/blur/issues/24

**Comment by who-biz** [comment]
The help text from this original issue has been amended in https://github.com/blur-network/blur/commit/12ae6ce7614fdbf8a67663875a7a10dffa32fb2a.  

I am going to leave this issue open, as a means for documenting the other prospective changes within keypair separation, and chacha20poly1305. We'll close it once those are completed.

**Comment by who-biz** [comment]
The help text from this original issue has been amended in commit https://github.com/blur-network/blur/commit/8a15a76846d5343e6d5d72cc50a2181b3647e5ad

I am going to leave this issue open, as a means for documenting the other prospective changes within keypair separation, and chacha20poly1305. We'll close it once those are completed.

Amended help text:
