### ISSUE TITLE
unspent_outputs N M does not seem to work

### ISSUE THREAD

**Issue by leto** [blur-network/blur#57]
I have various unspent outputs, when I try to filter the results to a range, the RPC does not seem to work. No matter what values of N and M I give, no results are returned.

**Comment by who-biz** [comment]
The command worked properly for me.  Upon issuing the command to a wallet, response `no unspent outputs for this address` is shown when the wallet doesn't have any UTXOs, and when issued to a wallet that does, it functioned properly as well.

Account for testing of the latter scenario, this wallet only had 1 output.  So, the issue may be related to the number of outs your wallet is trying to count.  Please also see comment in https://github.com/blur-network/blur/issues/58 as I believe they maybe related due to threads/memory use for counting of outs.

**Comment by who-biz** [comment]
Ah, nevermind.  It is due to the removal of the `std::` scope from the `size_t` type in various locations.  I'll add those back now, so we can move forward with a point release.

**Comment by who-biz** [comment]
Should be fixed in https://github.com/blur-network/blur/commit/ca825da1fbbaca514bd432b60ebde536c012a96c.  Let me know if the issue persists.  Closing this one for now.
