### ISSUE TITLE
You don't seem to understand. I place no value in blur. 

### ISSUE THREAD

**Issue by lazaridiscom** [blur-network/blur#80]
You don't seem to understand. I place no value in blur. I do place value in holding biz to account. He is a liar that tries to make a name for himself attacking other projects. All i am doing is giving him back what he so happily hands out

_Originally posted by @fart-master in https://github.com/blur-network/blur/issues/79#issuecomment-589907990_

I really think that you should focus on other platforms. E.g., the creators/teams around COSMOS are IT-fascists. Tezos has so much non-transparency that i'm wondering why the authorities in switzerland do not intervene.

Crypto is full of crap, leave biz alone, he's a nothing (not even worth a fart)

@who-biz, don't. Just don't close topics in a project with near-zero traffic.

You should lay back and pay visitors, whatever they're writing.

**Comment by who-biz** [comment]
You are free to do that elsewhere. This medium (issue tracker) is for issues in code. There are plenty of social places for chit-chat. 

Things posted here are for A.) My reference B.) The reference of potential contributors and C.) The reference of our users so that they may be informed about potential issues in software. 

Commentary and opinion have their place in their proper areas, too.
