### ISSUE TITLE
Block 991693?

### ISSUE THREAD

**Issue by trurebel** [blur-network/blur#86]
Hey

I compiled blurd on my two Ubuntus, 16 and 19, and both daemons are stuck at 991693 , any ideas?

**Comment by who-biz** [comment]
Database needs resized. Simply relaunch your daemon

**Comment by trurebel** [comment]
Wow, that's new! How often does this happen?

**Comment by who-biz** [comment]
According to LMDB’s documentation, on 64-bit systems, database should never need map resizing. So it’s somewhat odd that it needs to happen, in the first place.

But only about once every 1M blocks. Previously, it was happening much more frequently. We‘ll be adding some auto-resizing so that a manual restart is not necessary to trigger this.

**Comment by who-biz** [comment]
@trurebel as of commit: https://github.com/blur-network/blur/commit/ba05bbceef3cda880b32ef2a838858f57bc4c7e8, restarting a node is no longer necessary to trigger a map resize in LMDB. 

Initial allocation has been reduced substantially as well.
